version: "3"
services:
  app:
    image: docker-example:latest
    build:
      context: .
    ports:
      - "8080:8080"
    links:
      - redis
    environment:
      REDIS_URL: "redis://redis"
  redis:
    image: redis:latest

